name: Continuous Integration
on: [push]                     

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest     
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 
    
    - name: Build C# code
      run: dotnet build 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x' 
    
    - name: Install npm dependencies
      run: npm install
      working-directory: DotnetTemplate.Web
  
    - name: Build TypeScript code
      run: npm run build
      working-directory: DotnetTemplate.Web
    
    - name: Run C# tests
      run: dotnet test
  
    - name: Run TypeScript linter
      run: npm run lint
      working-directory: DotnetTemplate.Web

    - name: Run TypeScript tests
      run: npm t
      working-directory: DotnetTemplate.Web